// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBDMwDExh3CMTVvFphNZ9P5y1o6I0elGE',
    appId: '1:1098607667136:web:256d59423a539ac54d4a25',
    messagingSenderId: '1098607667136',
    projectId: 'project-1-5fddc',
    authDomain: 'project-1-5fddc.firebaseapp.com',
    storageBucket: 'project-1-5fddc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4CHP1MNJUd3zNL-0n5mw2lapQnxdO4YM',
    appId: '1:1098607667136:android:006201ae9a65742f4d4a25',
    messagingSenderId: '1098607667136',
    projectId: 'project-1-5fddc',
    storageBucket: 'project-1-5fddc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBusVamJNEJJ2av7qjs3AbQov34gBZ-148',
    appId: '1:1098607667136:ios:10b9f5a6d884f87b4d4a25',
    messagingSenderId: '1098607667136',
    projectId: 'project-1-5fddc',
    storageBucket: 'project-1-5fddc.firebasestorage.app',
    iosBundleId: 'com.example.thecafeelite',
  );
}
